[phases]
setup = "python310, postgresql_16.dev, gcc"
install = "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"
start = "python manage.py runserver 0.0.0.0:$PORT"
