[phases.setup]
packages = ["python310", "postgresql_16", "gcc"]

[phases.install]
commands = [
    "pip install -r requirements.txt",
    "python manage.py collectstatic --noinput"
]

[phases.start]
commands = [
    "gunicorn store.wsgi:application --bind 0.0.0.0:$PORT"
]
