[phases.setup]
packages = ["python310", "postgresql_16", "gcc"]

[phases.install]
commands = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install -r requirements.txt"
]

[phases.start]
commands = ["gunicorn store.wsgi:application --bind 0.0.0.0:$PORT"]


