[phases.setup]
packages = ["python310", "postgresql_16", "gcc"]

[phases.install]
commands = [
    "python -m venv /venv",
    ". /venv/bin/activate && pip install -r requirements.txt",
    ". /venv/bin/activate && python manage.py collectstatic --noinput"
]



[phases.start]
commands = [
    ". /venv/bin/activate && gunicorn store.wsgi:application --bind 0.0.0.0:$PORT"
]
